name = "mc3-modpack"
author = "Techgamr"
version = "1.0.1"
description = "Server mc3 modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "247cd3e559ffa940045723daed5e260382b15b549eb4be60af9ceb7db4f23307"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
