name = "mc3-modpack"
author = "Techgamr"
version = "1.0.0"
description = "Server mc3 modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d74f4623a9d1cf0cecd6b2945a7c14cf9c82c9fc425c14bfce5137ab2ab054d"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
